language: node_js
node_js:
  - "8"

sudo: false


addons:
  firefox: latest
  chrome: stable

os:
  - linux

install:
  - npm i -g npm@^5.3.0 && npm --version
  - npm install
  - npm run build.prod.aot -- --app pdr

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - scripts/testall.travis

after_script:
  - pkill gulp

cache:
  directories: node_modules

